
services:
  db:
    container_name: project-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: main_project_db
      MYSQL_USER: UMBCstudent
      MYSQL_PASSWORD: bongocat123
      MYSQL_ROOT_PASSWORD: bongocat123
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s     
      retries: 5

  www:
    container_name: project-www
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1.1-apache
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./:/var/www/html"
    ports:
      - "85:80"
      - "443:443"
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge